### ISSUE TITLE
Dropdown的Change事件中无法加入异步任务处理

### ISSUE THREAD

**Issue by sangyuxiaowu** [feiyun0112/Gradio.Net#10]
如果Change事件中存在await处理就会出现Task Cancelled错误，需要将其改为同步，是特性还是BUG呢？

```cs
model?.Change(change_models, inputs: [input, model], outputs: [model]);

...

static async Task<Output> change_models(Input input)
{
    await Task.Delay(1000);
   ....
}
```

![屏幕截图 2024-06-23 110109](https://github.com/feiyun0112/Gradio.Net/assets/17669599/b14ecaeb-5719-4a0c-bf92-d7cea2c9ad37)

**Comment by feiyun0112** [comment]
0.1.4 fixed

**Comment by sangyuxiaowu** [comment]
Gradio.Net.AspNetCore 未升级依赖
