### ISSUE TITLE
When using two textboxes in Gradio.NET, if the first textbox is set to `interactive=false`, the second textbox also becomes disabled.

### ISSUE THREAD

**Issue by sdcb** [feiyun0112/Gradio.Net#6]
**Description:**
When using two textboxes in Gradio.NET, if the first textbox is set to `interactive=false`, the second textbox also becomes disabled. This behavior is unexpected.

**Expected Behavior:**
The first textbox should be disabled, but the second textbox should remain interactive and functional.

**Code to Reproduce:**
Here is the sample code that demonstrates the issue:

```csharp
App.Launch(CreateBlocks());

Blocks CreateBlocks()
{
    using Blocks blocks = gr.Blocks();
    gr.Textbox("test", label: "WTF", interactive: false);
    gr.Textbox("test", label: "WTF");
    return blocks;
}
```

**Screenshot:**
<img width="667" alt="bug" src="https://github.com/feiyun0112/Gradio.Net/assets/1317141/d8f2023c-7cfa-4f91-90b8-3c83a609c9c4">

As shown in the screenshot, when the first textbox has `interactive=false`, the second textbox is also rendered as disabled.

**Steps to Reproduce:**
1. Use the provided code to launch the application.
2. Observe that both textboxes are disabled, even though only the first one is set with `interactive=false`.

**Additional Information:**
This issue might be related to how the interactive state is being propagated or mistakenly applied to subsequent components in the UI hierarchy. A closer inspection of the rendering logic or state management within the Gradio.NET framework might help identify the root cause.

Thank you for looking into this issue. Please let me know if you need any more information or clarification.

**Comment by feiyun0112** [comment]
gradio issue  [https://github.com/gradio-app/gradio/issues/8461](https://github.com/gradio-app/gradio/issues/8461)
